### ISSUE TITLE
Remove all console.log

### ISSUE THREAD

**Issue by milafrerichs** [boundlessgeo/geonode-elasticsearch#24]
I would advise removing all console.log statements.

First, IE does not like them. Second it clutters the test reports and makes it hard to find the failing tests. 

What do you think @ingenieroariel

**Comment by ingenieroariel** [comment]
I agree. Those are okay during development but should go away when the PR
is made.

**Comment by Lenninlasd** [comment]
I kept the statements that have some sort of error or important message, for example:

```javascript
if (timeValid === false) {
  console.log('----[ Warning: setTimeTickIndex called with time that is not ' +
                   'withing range of the provided index. ignoring time.', index, time);
  time = null;
}
```
