### ISSUE TITLE
ArcGIS Rest layers in Open Layers 3

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/geonode-elasticsearch#4]
- [x] Reproduce the following example locally: http://bartvde.github.io/ol3/esri-rest-experiment/examples/vector-esri.html
- [ ] Test the same layer in MapLoom with OL3

**Comment by lasdjs** [comment]
I can't reproduce de example, MapLoom has conflicts with later versions of ol3, and the proposed experiment run in later versions.

**Comment by ingenieroariel** [comment]
@lasdjs Can you specify which version it has and which version it needs?

**Comment by lasdjs** [comment]
Current v3.0.0,  version v3.8.1 needed.

**Comment by ingenieroariel** [comment]
I believe we are using a more recent OL3 now, let's check again.

**Comment by Lenninlasd** [comment]
The example was tested in Maploom, in the branch [ArcGIS-Rest-layers](https://github.com/terranodo/MapLoom/tree/ArcGIS-Rest-layers)

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/7197750/16284601/9e3289e8-3897-11e6-9154-b117325660a9.png)
