### ISSUE TITLE
Implement Reset button

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/geonode-elasticsearch#40]
- [x] Date range reset
- [x] Map Reset
- [x] Keyword reset

**Comment by Lenninlasd** [comment]
@ingenieroariel the Map Reset, is going to be implemented when https://github.com/boundlessgeo/exchange-search/issues/42 is ready, isn't it?

**Date range reset** and **Keyword reset** are included in the in PR : [#41](https://github.com/terranodo/MapLoom/pull/41)
