### ISSUE TITLE
Create Catalog model and tie pycsw and elastic search to it 

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/geonode-elasticsearch#45]

**Comment by panchicore** [comment]
@ingenieroariel tied elastic search by adding the catalog lists to the indexes, but dont undestand how to tie pycsw, provide instructions.

**Comment by ingenieroariel** [comment]
@panchicore pycsw code is living here: https://github.com/tomkralidis/HHypermap/blob/pycsw/hypermap/search/views.py#L17

What we need to do is to enable different /csw/<catalog name>/ endpoints and pass that variable to pycsw so that it can filter the list of layers that it operates against.

On your side, it is enough to wire up the urls.py to that view in  way that the catalog name comes up as a view variable.

**Comment by panchicore** [comment]
@ingenieroariel results something like:

http://localhost:8000/search/csw/**the-catalog-slug**/?request=GetRecords&service=CSW&version=2.0.2&resultType=results&outputSchema=http://www.isotc211.org/2005/gmd&typeNames=csw:Record&elementSetName=summary

https://github.com/terranodo/HHypermap/commit/a9314f48798675922df153e2249c91a24fbf9b97

**Comment by ingenieroariel** [comment]
@panchicore on the pycsw front it should be enough, but can you make sure on the elastic search front we have one index per catalog?
